UPDATE sracollector.pysradb_error_reference SET name = 'VALUE_ERROR'
WHERE name = 'KEY_ERROR';
UPDATE sracollector_dev.pysradb_error_reference SET name = 'VALUE_ERROR'
WHERE name = 'KEY_ERROR';
